### ISSUE TITLE
`H1Id` and `H1Null`

### ISSUE THREAD

**Issue by Mr-Andersen** [Ereski/generic-std#2]
I didn't manage to find these to "plugs" in your lib. I think they are pretty handy (for things like [this](https://gist.github.com/Mr-Andersen/a64833e1c5e5b6f40a00ce1b3bff54d1)) and basic, so it must be ok to include them in the std.

**Comment by Mr-Andersen** [comment]
Oh, I see that `H1Null` is just `H0<()>`. Nonetheless, there could be just a type alias right in the library.

**Comment by Ereski** [comment]
Yep, the `H0` struct is meant to cover this exact situation. For example, in the blanket implementation of `StreamingIterator` for `Iterator`s: https://github.com/Ereski/generic-std/blob/master/src/lib.rs#L181-L190

As a type alias I don't think it's worth, as I don't find `H0Null`/`H0Unit` any more descriptive than `H0<()>`. So I'm going to close this issue but feel free to reopen if you disagree ✌.

**Comment by Mr-Andersen** [comment]
What about `H1Id`?
